hard_tabs = false
tab_spaces = 2
reorder_imports = true
fn_args_layout = "Compressed"
fn_params_layout = "Compressed"
fn_single_line = true
control_brace_style = "ClosingNextLine"
# control_brace_style = "ClosingNextLine"
# control_brace_style = "ClosingNextLine"
# control_brace_style = "ClosingNextLine"
# control_brace_style = "ClosingNextLine"
